# Generated by Django 3.0.2 on 2020-01-25 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 25, 15, 24, 52, 477456, tzinfo=utc)),
        ),
    ]
