# Generated by Django 3.0.2 on 2020-01-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='ticket_number',
            field=models.CharField(default='O33FI1RH', editable=False, max_length=20, unique=True),
        ),
    ]
