# Generated by Django 3.0.2 on 2020-01-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eticketing', '0003_remove_order_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eticketing.Order'),
            preserve_default=False,
        ),
    ]
