# Generated by Django 3.0.2 on 2020-01-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticketing', '0004_auto_20200125_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='eticketing.OrderItem'),
        ),
    ]
