# Generated by Django 3.0.2 on 2020-02-07 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eticketing', '0007_auto_20200207_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eticketing.BillingAddress'),
        ),
    ]
