# Generated by Django 3.0.2 on 2020-01-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200119_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdate',
            old_name='event_data',
            new_name='event_date',
        ),
    ]
