# Generated by Django 3.0.2 on 2020-01-19 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200119_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('billing_address', models.CharField(max_length=100)),
                ('billing_zipcode', models.CharField(max_length=10)),
                ('billing_city', models.CharField(max_length=50)),
                ('billing_country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(default='787A6533', editable=False, max_length=20, unique=True)),
                ('attendee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='api.AttendeeType')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='api.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_orders', to='api.Customer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_orders', to='api.Event')),
            ],
        ),
    ]
